### ISSUE TITLE
Autenticação em Eventos

### ISSUE THREAD

**Issue by freitasmarc** [OpenSourceCommunityBrasil/RDWDemos#4]
Via URL um Evento marcado NeedAutorization com FALSE e no ServicePooler do Servidor com alguma Autenticação necessaria está funcionando. Mas nos exemplos da pasta DEMO, não. FullServer e Client

EXEMPLO DE SITUAÇÃO QUE NÃO FUNCIONA:
- ServicePooler com Autenticação BASICA
- Evento com Need marcado FALSE

EXEMPLO DE SITUAÇÃO QUE FUNCIONA:
- ServicePooler com Autenticação NONE
- Evento com Need marcado FALSE

Delphi 11.2

**Comment by mobius1qwe** [comment]
Corrigido na última atualização do trunk do componente, era um problema do componente, não do demo em si.
