### ISSUE TITLE
RESTDWClientSQL - Erro com campos Numeric e Float

### ISSUE THREAD

**Issue by lassistemas** [OpenSourceCommunityBrasil/RDWDemos#9]
Problemas com o RESTDWClientSQL ambiente Windows.

BinaryRequest ativado:
1 - Quando um campo é tipo NUMERIC e a escala é maior que 3, exemplo NUMERIC(13,4) apresenta o erro: "BCD overflow" 
![photo_2023-02-21_09-55-05](https://user-images.githubusercontent.com/102775670/220352434-c2b31f83-bbea-4908-b112-3312da93d561.jpg)

BinaryRequest ativo ou não:
2 - Quando adiciona um campo é tipo FLOAT usando o Field Editor (Campo vem direto do BD) apresenta o erro: "NOME DA TABELA filed NOME DO CAMPO is of unknown  type" 
![Campo Float](https://user-images.githubusercontent.com/102775670/220349977-aa17a3f2-0b02-471e-9398-2c2a19df39a3.png)

BinaryRequest desativado:
3- Quando tem campo OBRIGATÓRIO e tenta abrir a tebela.
![campo obrigatorio](https://user-images.githubusercontent.com/102775670/220354346-3fb9b459-c5ff-489f-b742-9701262bbb72.png)

**Comment by mobius1qwe** [comment]
Erro já corrigido em versões futuras
